package com.lima.apiserver.currentCenter.dao;

import com.lima.apiserver.currentCenter.entity.PlatformOauthRecord;
import com.lima.apiserver.currentCenter.entity.PlatformOauthRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PlatformOauthRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    long countByExample(PlatformOauthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    int deleteByExample(PlatformOauthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    @Delete({
        "delete from platform_oauth_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    @Insert({
        "insert into platform_oauth_record (id, oauth_client, ",
        "user_id, org_id, login_type, ",
        "oauth_username, oauth_type, ",
        "redirect_uri, oauth_source, ",
        "token_info, create_time, ",
        "is_del, platform, app_id, ",
        "app_version, request_ip, ",
        "device_id, handle_type, ",
        "handle_result, handle_type_desc, ",
        "timing, referer, ",
        "accept, origin, ",
        "user_agent)",
        "values (#{id,jdbcType=BIGINT}, #{oauthClient,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=BIGINT}, #{orgId,jdbcType=BIGINT}, #{loginType,jdbcType=TINYINT}, ",
        "#{oauthUsername,jdbcType=VARCHAR}, #{oauthType,jdbcType=VARCHAR}, ",
        "#{redirectUri,jdbcType=VARCHAR}, #{oauthSource,jdbcType=VARCHAR}, ",
        "#{tokenInfo,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isDel,jdbcType=TINYINT}, #{platform,jdbcType=CHAR}, #{appId,jdbcType=VARCHAR}, ",
        "#{appVersion,jdbcType=VARCHAR}, #{requestIp,jdbcType=VARCHAR}, ",
        "#{deviceId,jdbcType=VARCHAR}, #{handleType,jdbcType=TINYINT}, ",
        "#{handleResult,jdbcType=VARCHAR}, #{handleTypeDesc,jdbcType=VARCHAR}, ",
        "#{timing,jdbcType=INTEGER}, #{referer,jdbcType=VARCHAR}, ",
        "#{accept,jdbcType=VARCHAR}, #{origin,jdbcType=VARCHAR}, ",
        "#{userAgent,jdbcType=VARCHAR})"
    })
    int insert(PlatformOauthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    int insertSelective(PlatformOauthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    List<PlatformOauthRecord> selectByExample(PlatformOauthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    @Select({
        "select",
        "id, oauth_client, user_id, org_id, login_type, oauth_username, oauth_type, redirect_uri, ",
        "oauth_source, token_info, create_time, is_del, platform, app_id, app_version, ",
        "request_ip, device_id, handle_type, handle_result, handle_type_desc, timing, ",
        "referer, accept, origin, user_agent",
        "from platform_oauth_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.lima.apiserver.currentCenter.dao.PlatformOauthRecordMapper.BaseResultMap")
    PlatformOauthRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") PlatformOauthRecord record, @Param("example") PlatformOauthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    int updateByExample(@Param("record") PlatformOauthRecord record, @Param("example") PlatformOauthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    int updateByPrimaryKeySelective(PlatformOauthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_oauth_record
     *
     * @mbg.generated Fri Apr 19 13:55:47 CST 2019
     */
    @Update({
        "update platform_oauth_record",
        "set oauth_client = #{oauthClient,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "org_id = #{orgId,jdbcType=BIGINT},",
          "login_type = #{loginType,jdbcType=TINYINT},",
          "oauth_username = #{oauthUsername,jdbcType=VARCHAR},",
          "oauth_type = #{oauthType,jdbcType=VARCHAR},",
          "redirect_uri = #{redirectUri,jdbcType=VARCHAR},",
          "oauth_source = #{oauthSource,jdbcType=VARCHAR},",
          "token_info = #{tokenInfo,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_del = #{isDel,jdbcType=TINYINT},",
          "platform = #{platform,jdbcType=CHAR},",
          "app_id = #{appId,jdbcType=VARCHAR},",
          "app_version = #{appVersion,jdbcType=VARCHAR},",
          "request_ip = #{requestIp,jdbcType=VARCHAR},",
          "device_id = #{deviceId,jdbcType=VARCHAR},",
          "handle_type = #{handleType,jdbcType=TINYINT},",
          "handle_result = #{handleResult,jdbcType=VARCHAR},",
          "handle_type_desc = #{handleTypeDesc,jdbcType=VARCHAR},",
          "timing = #{timing,jdbcType=INTEGER},",
          "referer = #{referer,jdbcType=VARCHAR},",
          "accept = #{accept,jdbcType=VARCHAR},",
          "origin = #{origin,jdbcType=VARCHAR},",
          "user_agent = #{userAgent,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PlatformOauthRecord record);
}